//
//  QuranCentralData.swift
//  Dhikr
//
//  Hardcoded Quran Central reciter data.
//  Contains all known QC reciters with iTunes collectionIds where available.
//  Reciters with collectionId 0 need runtime discovery via iTunes search.
//

import Foundation

struct QCReciterEntry {
    let name: String
    let slug: String
    let collectionId: Int
}

enum QuranCentralData {
    /// All known Quran Central reciters.
    /// collectionId of 0 means the iTunes ID has not been discovered yet.
    static let allReciters: [QCReciterEntry] = [
        QCReciterEntry(name: "Aaar Al Hudhoudi", slug: "aaar-al-hudhoudi", collectionId: 1570438104),
        QCReciterEntry(name: "Abdallah Kamel", slug: "abdallah-kamel", collectionId: 1087737932),
        QCReciterEntry(name: "Abdel Aziz Al Ahmed", slug: "abdel-aziz-al-ahmed", collectionId: 733555281),
        QCReciterEntry(name: "Abdel Kawi Abdul Majid", slug: "abdel-kawi-abdul-majid", collectionId: 1571125367),
        QCReciterEntry(name: "Abdelaziz Sheim", slug: "abdelaziz-sheim", collectionId: 1832705700),
        QCReciterEntry(name: "Abdelhamid Hssain - Warsh", slug: "abdelhamid-hssain", collectionId: 1087739041),
        QCReciterEntry(name: "Abdelmoughit Maarouf - Warsh", slug: "abdelmoughit-maarouf-warsh", collectionId: 1832705915),
        QCReciterEntry(name: "Abdelmoujib Benkirane - Warsh", slug: "abdelmoujib-benkirane", collectionId: 1087739058),
        QCReciterEntry(name: "Abdul Azeez Ar Rawdhaan", slug: "abdul-azeez-ar-rawdhaan", collectionId: 1571125144),
        QCReciterEntry(name: "Abdul Aziz Abdullah Al Hamri", slug: "abdul-aziz-abdullah-al-hamri", collectionId: 1573557559),
        QCReciterEntry(name: "Abdul Bari Mohammed", slug: "abdul-bari-mohammed", collectionId: 1087738949),
        QCReciterEntry(name: "Abdul Basit", slug: "abdul-basit-abd-us-samad", collectionId: 598559251),
        QCReciterEntry(name: "Abdul Basit - Warsh", slug: "abdul-basit-warsh", collectionId: 1546238073),
        QCReciterEntry(name: "Abdul Fattah Shashaey", slug: "abdul-fattah-shashaey", collectionId: 1087760876),
        QCReciterEntry(name: "Abdul Kabeer Haidari", slug: "abdul-kabeer-haidari", collectionId: 1475482145),
        QCReciterEntry(name: "Abdul Latif Ismail Abdul Rahman", slug: "abdul-latif-ismail-abdul-rahman", collectionId: 1573558198),
        QCReciterEntry(name: "Abdul Mohsen Al Obeikan", slug: "abdul-mohsen-al-obeikan", collectionId: 1087761751),
        QCReciterEntry(name: "Abdul Muhsin Al Qasim", slug: "abdul-muhsin-al-qasim", collectionId: 1071230702),
        QCReciterEntry(name: "Abdul Muttalib Ibn Achoura - Asbahani", slug: "abdul-muttalib-ibn-achoura-asbahani", collectionId: 1546238559),
        QCReciterEntry(name: "Abdul Rahman Al Yusuf", slug: "abdul-rahman-al-yusuf", collectionId: 1087764628),
        QCReciterEntry(name: "Abdul Rahman Jamal Aloosi", slug: "abdul-rahman-jamal-aloosi", collectionId: 1087763394),
        QCReciterEntry(name: "Abdul Rahman Mossad", slug: "abdul-rahman-mossad", collectionId: 1832706009),
        QCReciterEntry(name: "Abdul Wali Al Arkani", slug: "abdul-wali-al-arkani", collectionId: 1087763207),
        QCReciterEntry(name: "Abdul-Munim Abdul-Mubdi", slug: "abdul-munim-abdul-mubdi", collectionId: 1087763417),
        QCReciterEntry(name: "Abdulaziz Al Suwaidan", slug: "abdulaziz-al-suwaidan", collectionId: 1087764316),
        QCReciterEntry(name: "Abdulaziz Az-Zahrani", slug: "abdulaziz-az-zahrani", collectionId: 1087762987),
        QCReciterEntry(name: "AbdulBari ath-Thubaity", slug: "abdulbari-ath-thubaity", collectionId: 796967163),
        QCReciterEntry(name: "Abdulbaset Abulazm", slug: "abdulbaset-abulazm", collectionId: 1832705852),
        QCReciterEntry(name: "Abdulghani Abdullah", slug: "abdulghani-abdullah", collectionId: 1087762988),
        QCReciterEntry(name: "Abdulhadi Kanakeri", slug: "abdulhadi-kanakeri", collectionId: 1087766019),
        QCReciterEntry(name: "Abdulkabir Al Hadidi", slug: "abdulkabir-al-hadidi", collectionId: 1087763869),
        QCReciterEntry(name: "Abdullah Al Buajan", slug: "abdullah-al-buajan", collectionId: 1087763879),
        QCReciterEntry(name: "Abdullah Al Buraimi", slug: "abdullah-al-buraimi", collectionId: 1087764813),
        QCReciterEntry(name: "Abdullah Al Khalaf", slug: "abdullah-al-khalaf", collectionId: 1757809184),
        QCReciterEntry(name: "Abdullah Basfar", slug: "abdullah-basfar", collectionId: 1020163254),
        QCReciterEntry(name: "Abdullah Fahmi", slug: "abdullah-fahmi", collectionId: 1087765073),
        QCReciterEntry(name: "Abdullah Ghailan", slug: "abdullah-ghailan", collectionId: 1087765319),
        QCReciterEntry(name: "Abdullah Khayat", slug: "abdullah-khayat", collectionId: 815757924),
        QCReciterEntry(name: "Abdullah Khulaifi", slug: "abdullah-khulaifi", collectionId: 1570419968),
        QCReciterEntry(name: "Abdullah Salah Abou Al Fotouh", slug: "abdullah-salah-abou-al-fotouh", collectionId: 1087765331),
        QCReciterEntry(name: "Abdullahi Abba Zaria", slug: "abdullahi-abba-zaria", collectionId: 1546236196),
        QCReciterEntry(name: "Abdullahi Abba Zaria - [Khalaf]", slug: "abdullahi-abba-zaria-khalaf", collectionId: 1546236196),
        QCReciterEntry(name: "Abdulmohsen Al-Askar", slug: "abdulmohsen-al-askar", collectionId: 1087765194),
        QCReciterEntry(name: "Abdulmohsen Al-Harthy", slug: "abdulmohsen-al-harthy", collectionId: 1087784497),
        QCReciterEntry(name: "Abdur Rahman As-Sudais", slug: "abdur-rahman-as-sudais", collectionId: 1020160983),
        QCReciterEntry(name: "Abdur Rasheed Sufi - [Abi al-Haarith an al-Kasaaee]", slug: "abdur-rasheed-sufi-abi-al-haarith", collectionId: 626277401),
        QCReciterEntry(name: "Abdur Rasheed Sufi - [ad-Doori an Abi Amr]", slug: "abdur-rasheed-sufi-ad-doori", collectionId: 626277401),
        QCReciterEntry(name: "Abdur Rasheed Sufi - [Khalaf]", slug: "abdur-rasheed-sufi-khalaf", collectionId: 626277401),
        QCReciterEntry(name: "Abdur Rasheed Sufi - [Shubah an Asim]", slug: "abdur-rasheed-sufi-shubah", collectionId: 626277401),
        QCReciterEntry(name: "Abdur Rasheed Sufi - [Soosi]", slug: "abdur-rasheed-sufi-soosi", collectionId: 626277401),
        QCReciterEntry(name: "Abdur Razaq Bin Abtan Al Dulaimi", slug: "abdur-razaq-bin-abtan-al-dulaimi", collectionId: 1087815759),
        QCReciterEntry(name: "Abdurrahim Abdussalam An-Nabulsi", slug: "abdurrahim-abdussalam-an-nabulsi", collectionId: 1087815368),
        QCReciterEntry(name: "Abu Abdullah Munir Al Tounsi", slug: "abu-abdullah-munir-al-tounsi", collectionId: 1087827589),
        QCReciterEntry(name: "Abu Bakr al-Shatri", slug: "abu-bakr-al-shatri", collectionId: 622736701),
        QCReciterEntry(name: "Abu Usamah Syamsul Hadi", slug: "abu-usamah-syamsul-hadi", collectionId: 1546237625),
        QCReciterEntry(name: "Abubakar-Sadiq Zakariyya", slug: "abubakar-sadiq-zakariyya", collectionId: 1757810013),
        QCReciterEntry(name: "Adil Kalbani", slug: "adil-kalbani", collectionId: 1020158010),
        QCReciterEntry(name: "Adil Rayane", slug: "adil-rayane", collectionId: 1087817599),
        QCReciterEntry(name: "Ahmad Al Hawashy", slug: "ahmad-al-hawashy", collectionId: 1087913642),
        QCReciterEntry(name: "Ahmad Alnufais", slug: "ahmad-alnufais", collectionId: 1570435019),
        QCReciterEntry(name: "Ahmad Khader Al-Tarabulsi", slug: "ahmad-khader-al-tarabulsi", collectionId: 1087913110),
        QCReciterEntry(name: "Ahmad Naina", slug: "ahmad-naina", collectionId: 1087817751),
        QCReciterEntry(name: "Ahmad Sulaiman", slug: "ahmad-sulaiman", collectionId: 1570438292),
        QCReciterEntry(name: "Ahmad Taleb Hameed", slug: "ahmad-taleb-hameed", collectionId: 1570438414),
        QCReciterEntry(name: "Ahmed Abou Kasmi", slug: "ahmed-abou-kasmi", collectionId: 1087818022),
        QCReciterEntry(name: "Ahmed Aissa El Masarawi", slug: "ahmed-aissa-el-masarawi", collectionId: 1087817601),
        QCReciterEntry(name: "Ahmed Akl", slug: "ahmed-akl", collectionId: 1087818043),
        QCReciterEntry(name: "Ahmed Al Ajmi", slug: "ahmed-al-ajmi", collectionId: 1071231130),
        QCReciterEntry(name: "Ahmed Al Misbahi", slug: "ahmed-al-misbahi", collectionId: 1087915662),
        QCReciterEntry(name: "Ahmed Al-Huthaify", slug: "ahmed-al-huthaify", collectionId: 1087818742),
        QCReciterEntry(name: "Ahmed Amir", slug: "ahmed-amir", collectionId: 1087915669),
        QCReciterEntry(name: "Ahmed Mohamed Salama", slug: "ahmed-mohamed-salama", collectionId: 1087913925),
        QCReciterEntry(name: "Ahmed Ragab", slug: "ahmed-ragab", collectionId: 1087818876),
        QCReciterEntry(name: "Ahmed Saber", slug: "ahmed-saber", collectionId: 1087913720),
        QCReciterEntry(name: "Ahmed Saeed Mandour", slug: "ahmed-saeed-mandour", collectionId: 1087818351),
        QCReciterEntry(name: "Ahmed Saoud", slug: "ahmed-saoud", collectionId: 1087818553),
        QCReciterEntry(name: "Aiman Ridhwan", slug: "aiman-ridhwan", collectionId: 1832706043),
        QCReciterEntry(name: "Akhil Abdulhay Rawa", slug: "akhil-abdulhay-rawa", collectionId: 1087818496),
        QCReciterEntry(name: "Akram Al Aalakmi", slug: "akram-al-aalakmi", collectionId: 1087820130),
        QCReciterEntry(name: "Al Ashry Omran", slug: "al-ashry-omran", collectionId: 1087921910),
        QCReciterEntry(name: "Al Fateh Muhammad Zubair", slug: "al-fateh-muhammad-zubair", collectionId: 1087922346),
        QCReciterEntry(name: "Al Husayni Al Azazi", slug: "al-husayni-al-azazi", collectionId: 1087818691),
        QCReciterEntry(name: "Al Husayni Al Azazi - Children", slug: "al-husayni-al-azazi-children", collectionId: 1087818691),
        QCReciterEntry(name: "Ali Abdur-Rahman al-Huthaify", slug: "ali-abdur-rahman-al-huthaify", collectionId: 732074019),
        QCReciterEntry(name: "Ali Abdur-Rahman al-Huthaify - [Qaloon]", slug: "ali-abdur-rahman-al-huthaify-qaloon", collectionId: 1561931440),
        QCReciterEntry(name: "Ali Abu Hashem", slug: "ali-abu-hashem", collectionId: 1087818563),
        QCReciterEntry(name: "Ali Barrak", slug: "ali-barrak", collectionId: 1087818837),
        QCReciterEntry(name: "Ali Hajjaj Souissi", slug: "ali-hajjaj-souissi", collectionId: 1087818566),
        QCReciterEntry(name: "Alzain Mohamed Ahmed", slug: "alzain-mohamed-ahmed", collectionId: 1087820319),
        QCReciterEntry(name: "Amir Al Mohalhal", slug: "amir-al-mohalhal", collectionId: 1087821077),
        QCReciterEntry(name: "Anas Al Emadi", slug: "anas-al-emadi", collectionId: 1087820706),
        QCReciterEntry(name: "Anas Almiman", slug: "anas-almiman", collectionId: 1570439023),
        QCReciterEntry(name: "Anas El Ghamidi", slug: "anas-el-ghamidi", collectionId: 1087820181),
        QCReciterEntry(name: "Antar Muslim", slug: "antar-muslim", collectionId: 1087820316),
        QCReciterEntry(name: "Ayman Swed", slug: "ayman-swed", collectionId: 1087819290),
        QCReciterEntry(name: "Ayoob Essack", slug: "ayoob-essack", collectionId: 1467164151),
        QCReciterEntry(name: "Aziz Alili", slug: "aziz-alili", collectionId: 815009119),
        QCReciterEntry(name: "Baasem bin Muhammad As-Subayee", slug: "baasem-bin-muhammad-as-subayee", collectionId: 1832705827),
        QCReciterEntry(name: "Badr Al Ali", slug: "badr-al-ali", collectionId: 1570439204),
        QCReciterEntry(name: "Badr Al-Turki", slug: "badr-al-turki", collectionId: 1757808956),
        QCReciterEntry(name: "Bandar Al Yousr", slug: "bandar-al-yousr", collectionId: 1576195680),
        QCReciterEntry(name: "Bandar Baleela", slug: "bandar-baleela", collectionId: 1087821071),
        QCReciterEntry(name: "Bassel Abdul Rahman Raoui", slug: "bassel-abdul-rahman-raoui", collectionId: 1087820702),
        QCReciterEntry(name: "Dawood Hamza", slug: "dawood-hamza", collectionId: 1087821627),
        QCReciterEntry(name: "Egzon Ibrahimi", slug: "egzon-ibrahimi", collectionId: 1832705939),
        QCReciterEntry(name: "Eid Hassan Abu Aachra", slug: "eid-hassan-abu-aachra", collectionId: 1087820599),
        QCReciterEntry(name: "Eidi Shaban", slug: "eidi-shaban", collectionId: 1832705940),
        QCReciterEntry(name: "Emad Al Mansary", slug: "emad-al-mansary", collectionId: 1087820993),
        QCReciterEntry(name: "Fahad Al-Otaibi", slug: "fahad-al-otaibi", collectionId: 1087821044),
        QCReciterEntry(name: "Fahd Al Kandari", slug: "fahd-al-kandari", collectionId: 1087821045),
        QCReciterEntry(name: "Faisal Al Ghazzawi", slug: "faisal-al-ghazzawi", collectionId: 1570450916),
        QCReciterEntry(name: "Faisal Al-Halabi", slug: "faisal-al-halabi", collectionId: 1087820751),
        QCReciterEntry(name: "Fares Abbad", slug: "fares-abbad", collectionId: 1020157644),
        QCReciterEntry(name: "Fatih Seferagic", slug: "fatih-seferagic", collectionId: 1087820759),
        QCReciterEntry(name: "Fawaz Al Kaabi", slug: "fawaz-al-kaabi", collectionId: 1087821046),
        QCReciterEntry(name: "Faysal Wizar", slug: "faysal-wizar", collectionId: 1087821885),
        QCReciterEntry(name: "Fouad Al Khamiri", slug: "fouad-al-khamiri", collectionId: 1087821881),
        QCReciterEntry(name: "Haitham Al Dokhin", slug: "haitham-al-dokhin", collectionId: 1769180127),
        QCReciterEntry(name: "Haitham Al-Rifai", slug: "haitham-al-rifai", collectionId: 1832706188),
        QCReciterEntry(name: "Hamad Al Daghriri", slug: "hamad-al-daghriri", collectionId: 1087822261),
        QCReciterEntry(name: "Hamad Sinan", slug: "hamad-sinan", collectionId: 815002509),
        QCReciterEntry(name: "Hammam Abdel Fattah Tawfiq", slug: "hammam-abdel-fattah-tawfiq", collectionId: 1087822269),
        QCReciterEntry(name: "Hani Abdallah", slug: "hani-abdallah", collectionId: 1087821056),
        QCReciterEntry(name: "Hani Ar Rifai", slug: "hani-ar-rifai", collectionId: 1020157588),
        QCReciterEntry(name: "Hasan Al-Husaini", slug: "hasan-al-husaini", collectionId: 1087822931),
        QCReciterEntry(name: "Hasan Ali Moraib", slug: "hasan-ali-moraib", collectionId: 1087822911),
        QCReciterEntry(name: "Hassan Adly", slug: "hassan-adly", collectionId: 1588901188),
        QCReciterEntry(name: "Hassan Mahmoud Al Kholi", slug: "hassan-mahmoud-al-kholi", collectionId: 1832705761),
        QCReciterEntry(name: "Hassan Saleh", slug: "hassan-saleh", collectionId: 1087821904),
        QCReciterEntry(name: "Hatem Fareed Alwaer", slug: "hatem-fareed-alwaer", collectionId: 1087823324),
        QCReciterEntry(name: "Hatem Farid", slug: "hatem-farid", collectionId: 1020157544),
        QCReciterEntry(name: "Hazza Al Balushi", slug: "hazza-al-balushi", collectionId: 1475482826),
        QCReciterEntry(name: "Hesham Abdelbary", slug: "hesham-abdelbary", collectionId: 1087823823),
        QCReciterEntry(name: "Hossein Bousseksso", slug: "hossein-bousseksso", collectionId: 1087823437),
        QCReciterEntry(name: "Hussam Siddiq Khoja", slug: "hussam-siddiq-khoja", collectionId: 1547576833),
        QCReciterEntry(name: "Hussein Al-Sheikh", slug: "hussein-al-sheikh", collectionId: 1087823831),
        QCReciterEntry(name: "Ibi Idris", slug: "ibi-idris", collectionId: 1832706227),
        QCReciterEntry(name: "Ibrahem Assadan", slug: "ibrahem-assadan", collectionId: 1087823708),
        QCReciterEntry(name: "Ibrahim Abdelfatah Al Chaachai", slug: "ibrahim-abdelfatah-al-chaachai", collectionId: 1087821906),
        QCReciterEntry(name: "Ibrahim Al Akhdar", slug: "ibrahim-al-akhdar", collectionId: 816473125),
        QCReciterEntry(name: "Ibrahim Al Asiri", slug: "ibrahim-al-asiri", collectionId: 1087824220),
        QCReciterEntry(name: "Ibrahim Al-Dossari", slug: "ibrahim-al-dossari", collectionId: 1087824212),
        QCReciterEntry(name: "Ibrahim Al-Jibreen", slug: "ibrahim-al-jibreen", collectionId: 1095702463),
        QCReciterEntry(name: "Ibrahim Aljormy", slug: "ibrahim-aljormy", collectionId: 1087823993),
        QCReciterEntry(name: "Ibrahim Ramadan Shaaban", slug: "ibrahim-ramadan-shaaban", collectionId: 1087825124),
        QCReciterEntry(name: "Ibrahim Walk - English Only", slug: "ibrahim-walk-english-only", collectionId: 1510224829),
        QCReciterEntry(name: "Idris Shihiro - Warsh", slug: "idris-shihiro", collectionId: 1832706260),
        QCReciterEntry(name: "Idriss Abkar", slug: "idriss-abkar", collectionId: 1087824431),
        QCReciterEntry(name: "Ilhan Tok", slug: "ilhan-tok", collectionId: 1087825635),
        QCReciterEntry(name: "Imad Zuhair Hafez", slug: "imad-zuhair-hafez", collectionId: 815125307),
        QCReciterEntry(name: "IsHaaq Jasat", slug: "ishaaq-jasat", collectionId: 1386748073),
        QCReciterEntry(name: "Islam Sobhi", slug: "islam-sobhi", collectionId: 1570440204),
        QCReciterEntry(name: "Ismail Annuri", slug: "ismail-annuri", collectionId: 1546237745),
        QCReciterEntry(name: "Ismail Londt", slug: "ismail-londt", collectionId: 1762263668),
        QCReciterEntry(name: "Ja'afar Mahmud Adam", slug: "jaafar-mahmud-adam", collectionId: 1546357481),
        QCReciterEntry(name: "Jaber Abdul Hameed", slug: "jaber-abdul-hameed", collectionId: 1087828539),
        QCReciterEntry(name: "Jamaan Alosaimi", slug: "jamaan-alosaimi", collectionId: 1087828532),
        QCReciterEntry(name: "Jamal Addeen Alzailaie", slug: "jamal-addeen-alzailaie", collectionId: 1087830427),
        QCReciterEntry(name: "Jamal Shaker Abdullah", slug: "jamal-shaker-abdullah", collectionId: 1087831309),
        QCReciterEntry(name: "Karim Mansouri", slug: "karim-mansouri", collectionId: 1087832525),
        QCReciterEntry(name: "Khaled Abu Shady", slug: "khaled-abu-shady", collectionId: 1087831634),
        QCReciterEntry(name: "Khaled Al Qahtani", slug: "khaled-al-qahtani", collectionId: 1020157263),
        QCReciterEntry(name: "Khalid Abdulkafi", slug: "khalid-abdulkafi", collectionId: 1087832041),
        QCReciterEntry(name: "Khalid Al Ghamdi", slug: "khalid-al-ghamdi", collectionId: 1087832776),
        QCReciterEntry(name: "Khalid Al Jalil", slug: "khalid-al-jalil", collectionId: 1087831900),
        QCReciterEntry(name: "Khalid Al Mohanna", slug: "khalid-al-mohanna", collectionId: 1087833191),
        QCReciterEntry(name: "Khalid Al-Wahaibi", slug: "khalid-al-wahaibi", collectionId: 1087834230),
        QCReciterEntry(name: "Khalid Ar-Rashid", slug: "khalid-ar-rashid", collectionId: 1832706142),
        QCReciterEntry(name: "Khalifa Al Tunaiji", slug: "khalifa-al-tunaiji", collectionId: 1087833278),
        QCReciterEntry(name: "Laayoun El Kouchi", slug: "laayoun-el-kouchi", collectionId: 1087833003),
        QCReciterEntry(name: "Lafi Al Oni", slug: "lafi-al-oni", collectionId: 1087834529),
        QCReciterEntry(name: "Maajid Zibin", slug: "maajid-zibin", collectionId: 1598075209),
        QCReciterEntry(name: "Maher Al Mueaqly", slug: "maher-al-mueaqly", collectionId: 605798891),
        QCReciterEntry(name: "Maher Shakhashiro", slug: "maher-shakhashiro", collectionId: 1087835285),
        QCReciterEntry(name: "Mahmood Al Rifai", slug: "mahmood-al-rifai", collectionId: 1087836494),
        QCReciterEntry(name: "Mahmood Al-Tabib", slug: "mahmood-al-tabib", collectionId: 1087835840),
        QCReciterEntry(name: "Mahmood Khaleel Al Qari", slug: "mahmood-khaleel-al-qari", collectionId: 1561931504),
        QCReciterEntry(name: "Mahmood Shahat", slug: "mahmood-shahat", collectionId: 1087837193),
        QCReciterEntry(name: "Mahmoud Abu Al-Wafa al-Saidi", slug: "mahmoud-abu-al-wafa-al-saidi", collectionId: 1087836679),
        QCReciterEntry(name: "Mahmoud Ali Al Banna", slug: "mahmoud-ali-al-banna", collectionId: 1087836897),
        QCReciterEntry(name: "Mahmoud El Sheimy", slug: "mahmoud-el-sheimy", collectionId: 1087836366),
        QCReciterEntry(name: "Mahmoud Idriss", slug: "mahmoud-idriss", collectionId: 1087836933),
        QCReciterEntry(name: "Mahmoud Khalil Al-Husary", slug: "mahmoud-khalil-al-husary", collectionId: 1020156851),
        QCReciterEntry(name: "Mahmoud Khalil Al-Husary - [Doori]", slug: "mahmoud-khalil-al-husary-doori", collectionId: 1561931530),
        QCReciterEntry(name: "Mahmoud Khalil Al-Husary - Warsh", slug: "mahmoud-khalil-al-husary-warsh", collectionId: 1546238736),
        QCReciterEntry(name: "Mahmoud Moujahid", slug: "mahmoud-moujahid", collectionId: 1087836427),
        QCReciterEntry(name: "Mahmoud Saad Darouich", slug: "mahmoud-saad-darouich", collectionId: 1087838145),
        QCReciterEntry(name: "Mahmoud Sayed Eltayeb", slug: "mahmoud-sayed-eltayeb", collectionId: 1087837546),
        QCReciterEntry(name: "Majed Al-Zamil", slug: "majed-al-zamil", collectionId: 1087839584),
        QCReciterEntry(name: "Malek Shaiba Alhamd", slug: "malek-shaiba-alhamd", collectionId: 1087840155),
        QCReciterEntry(name: "Mansour Al Salimi", slug: "mansour-al-salimi", collectionId: 1570605672),
        QCReciterEntry(name: "Marwan Salam", slug: "marwan-salam", collectionId: 1087840489),
        QCReciterEntry(name: "Mishary Rashid Alafasy", slug: "mishary-rashid-alafasy", collectionId: 625975033),
        QCReciterEntry(name: "Moeedh Alharthi", slug: "moeedh-alharthi", collectionId: 1087841602),
        QCReciterEntry(name: "Mohamad al-Arefe", slug: "mohamad-al-arefe", collectionId: 1087841948),
        QCReciterEntry(name: "Mohamed Abdel Hakim Saad Al Abdullah", slug: "mohamed-abdel-hakim-saad-al-abdullah", collectionId: 1087842876),
        QCReciterEntry(name: "Mohamed Abdel Samia Raslan", slug: "mohamed-abdel-samia-raslan", collectionId: 1087842757),
        QCReciterEntry(name: "Mohamed Abdelaziz", slug: "mohamed-abdelaziz", collectionId: 1087843378),
        QCReciterEntry(name: "Mohamed Al Mohisni", slug: "mohamed-al-mohisni", collectionId: 1087844443),
        QCReciterEntry(name: "Mohamed Al Tayeb Hamdan", slug: "mohamed-al-tayeb-hamdan", collectionId: 1087843951),
        QCReciterEntry(name: "Mohamed Al-Ghurbani", slug: "mohamed-al-ghurbani", collectionId: 1087844770),
        QCReciterEntry(name: "Mohamed Aljabery Al Heyani", slug: "mohamed-aljabery-al-heyani", collectionId: 1087845635),
        QCReciterEntry(name: "Mohamed Awad Al-Harbawi", slug: "mohamed-awad-al-harbawi", collectionId: 1832706120),
        QCReciterEntry(name: "Mohamed Chahboun", slug: "mohamed-chahboun", collectionId: 1087844461),
        QCReciterEntry(name: "Mohamed El Barak", slug: "mohamed-el-barak", collectionId: 1087845143),
        QCReciterEntry(name: "Mohamed El Iraoui", slug: "mohamed-el-iraoui", collectionId: 1087847029),
        QCReciterEntry(name: "Mohamed El Kantaoui", slug: "mohamed-el-kantaoui", collectionId: 1087846011),
        QCReciterEntry(name: "Mohamed Emad Abdel Fattah", slug: "mohamed-emad-abdel-fattah", collectionId: 1087846052),
        QCReciterEntry(name: "Mohamed Farid Alsendiony", slug: "mohamed-farid-alsendiony", collectionId: 1087846960),
        QCReciterEntry(name: "Mohamed Hassan", slug: "mohamed-hassan", collectionId: 823600731),
        QCReciterEntry(name: "Mohamed Maabad", slug: "mohamed-maabad", collectionId: 1087847542),
        QCReciterEntry(name: "Mohamed Osman Khan", slug: "mohamed-osman-khan", collectionId: 1087847865),
        QCReciterEntry(name: "Mohamed Shaaban Abu Qarn", slug: "mohamed-shaaban-abu-qarn", collectionId: 1087848491),
        QCReciterEntry(name: "Mohamed Shaheem Ali Saeed", slug: "mohamed-shaheem-ali-saeed", collectionId: 1313850998),
        QCReciterEntry(name: "Mohamed Tablawi", slug: "mohamed-tablawi", collectionId: 817313773),
        QCReciterEntry(name: "Mohammad Almonshed", slug: "mohammad-almonshed", collectionId: 1087848738),
        QCReciterEntry(name: "Mohammad Ismaeel Al-Muqaddim", slug: "mohammad-ismaeel-al-muqaddim", collectionId: 817330228),
        QCReciterEntry(name: "Mohammad Moussa Hamdan", slug: "mohammad-moussa-hamdan", collectionId: 1087848634),
        QCReciterEntry(name: "Mohammad Rachad Al Shareef", slug: "mohammad-rachad-al-shareef", collectionId: 1087849099),
        QCReciterEntry(name: "Mohammed Ayoub Abu Mazen", slug: "mohammed-ayoub-abu-mazen", collectionId: 1087848969),
        QCReciterEntry(name: "Mohammed Bin Saleh Abu Zaid", slug: "mohammed-bin-saleh-abu-zaid", collectionId: 1087849081),
        QCReciterEntry(name: "Mohammed Hafas Ali", slug: "mohammed-hafas-ali", collectionId: 1087849449),
        QCReciterEntry(name: "Mohammed Hashim Abdul Aziz", slug: "mohammed-hashim-abdul-aziz", collectionId: 1087849643),
        QCReciterEntry(name: "Mohammed Mustafa Al Zayat", slug: "mohammed-mustafa-al-zayat", collectionId: 1087849506),
        QCReciterEntry(name: "Mohanad Salem", slug: "mohanad-salem", collectionId: 1087850028),
        QCReciterEntry(name: "Mohy El-Din Al Kourdi", slug: "mohy-el-din-al-kourdi", collectionId: 1087849930),
        QCReciterEntry(name: "Mouhamad Hady Toure", slug: "mouhamad-hady-toure", collectionId: 1475482461),
        QCReciterEntry(name: "Moussa Hassan Mayan", slug: "moussa-hassan-mayan", collectionId: 1087850546),
        QCReciterEntry(name: "Muayyid Al Mazen", slug: "muayyid-al-mazen", collectionId: 1087850739),
        QCReciterEntry(name: "Muflih Safitra", slug: "muflih-safitra", collectionId: 1546237718),
        QCReciterEntry(name: "Muftah Alsaltany", slug: "muftah-alsaltany", collectionId: 1087850934),
        QCReciterEntry(name: "Mufti Ismail Menk", slug: "mufti-ismail-menk", collectionId: 1086314758),
        QCReciterEntry(name: "Muhammad Abdul Kareem", slug: "muhammad-abdul-kareem", collectionId: 817339061),
        QCReciterEntry(name: "Muhammad Abdul Qadir Al-Hassan", slug: "muhammad-abdul-qadir-al-hassan", collectionId: 1832706241),
        QCReciterEntry(name: "Muhammad Al Subayyil", slug: "muhammad-al-subayyil", collectionId: 1570605662),
        QCReciterEntry(name: "Muhammad Al-Aalim Al-Dokali", slug: "muhammad-al-aalim-al-dokali", collectionId: 1087851183),
        QCReciterEntry(name: "Muhammad Al-Faqih", slug: "muhammad-al-faqih", collectionId: 1757810054),
        QCReciterEntry(name: "Muhammad Al-Hafiz", slug: "muhammad-al-hafiz", collectionId: 1087851929),
        QCReciterEntry(name: "Muhammad Al-Luhaidan", slug: "muhammad-al-luhaidan", collectionId: 823602911),
        QCReciterEntry(name: "Muhammad al-Mehysni", slug: "muhammad-al-mehysni", collectionId: 1757810557),
        QCReciterEntry(name: "Muhammad Anwar Shahat", slug: "muhammad-anwar-shahat", collectionId: 1087851128),
        QCReciterEntry(name: "Muhammad Ayyub", slug: "muhammad-ayyub", collectionId: 817316993),
        QCReciterEntry(name: "Muhammad Dibirov", slug: "muhammad-dibirov", collectionId: 1832706398),
        QCReciterEntry(name: "Muhammad Ghazali", slug: "muhammad-ghazali", collectionId: 1561931689),
        QCReciterEntry(name: "Muhammad Khaleel Al-Qari", slug: "muhammad-khaleel", collectionId: 1561931743),
        QCReciterEntry(name: "Muhammad Saleh Alim Shah", slug: "muhammad-saleh-alim-shah", collectionId: 1087852246),
        QCReciterEntry(name: "Muhammad Siddiq al-Minshawi", slug: "muhammad-siddiq-al-minshawi", collectionId: 627888500),
        QCReciterEntry(name: "Muhammad Siddiq al-Minshawi - Child Repeat", slug: "muhammad-siddiq-al-minshawi-child-repeat", collectionId: 1757810676),
        QCReciterEntry(name: "Muhammad Siddiq al-Minshawi - Mujawwad", slug: "muhammad-siddiq-al-minshawi-mujawwad", collectionId: 1561931747),
        QCReciterEntry(name: "Muhammad Sulaiman Patel", slug: "muhammad-sulaiman-patel", collectionId: 1561932044),
        QCReciterEntry(name: "Muhammad Taha Al Junaid", slug: "muhammad-taha-al-junaid", collectionId: 1087852151),
        QCReciterEntry(name: "Muhammad Zarami", slug: "muhammad-zarami", collectionId: 1546357425),
        QCReciterEntry(name: "Muhammed Khairul Anour", slug: "muhammed-khairul-anour", collectionId: 1087851806),
        QCReciterEntry(name: "Muiz Bukhary", slug: "muiz-bukhary", collectionId: 1130799988),
        QCReciterEntry(name: "Musa Bilal", slug: "musa-bilal", collectionId: 1087851815),
        QCReciterEntry(name: "Mustafa Al Lahouni", slug: "mustafa-al-lahouni", collectionId: 845731765),
        QCReciterEntry(name: "Mustafa Al-Ardy", slug: "mustafa-al-ardy", collectionId: 1832706344),
        QCReciterEntry(name: "Mustafa Ismail", slug: "mustafa-ismail", collectionId: 817316135),
        QCReciterEntry(name: "Mustafa Raad Al Azzawi", slug: "mustafa-raad-al-azzawi", collectionId: 823603903),
        QCReciterEntry(name: "Mustapha Gharbi", slug: "mustapha-gharbi", collectionId: 1087852841),
        QCReciterEntry(name: "Nabil Ar Rifai", slug: "nabil-ar-rifai", collectionId: 823603904),
        QCReciterEntry(name: "Nadeem Dawood", slug: "nadeem-dawood", collectionId: 1397142373),
        QCReciterEntry(name: "Nafiu Usman Bauchi", slug: "nafiu-usman-bauchi", collectionId: 1757810876),
        QCReciterEntry(name: "Nasir Bin Ali Al Ghamdi", slug: "nasir-bin-ali-al-ghamdi", collectionId: 1087852933),
        QCReciterEntry(name: "Nasser Al Obaid", slug: "nasser-al-obaid", collectionId: 1087852261),
        QCReciterEntry(name: "Nasser Al Qatami", slug: "nasser-al-qatami", collectionId: 823603482),
        QCReciterEntry(name: "Neamah Al-Hassan", slug: "neamah-al-hassan", collectionId: 1087853711),
        QCReciterEntry(name: "Noreen Muhammad Siddique - Al-Duri via Abu Amr", slug: "noreen-muhammad-siddique", collectionId: 1544614138),
        QCReciterEntry(name: "Omar Ahmed Abdul Rahman", slug: "omar-ahmed-abdul-rahman", collectionId: 1607275256),
        QCReciterEntry(name: "Omar al Darweez", slug: "omar-al-darweez", collectionId: 1544215774),
        QCReciterEntry(name: "Omar Al Kazabri", slug: "omar-al-kazabri", collectionId: 1087854160),
        QCReciterEntry(name: "Omar Hassan Saleh", slug: "omar-hassan-saleh", collectionId: 1832706407),
        QCReciterEntry(name: "Omar Hisham Al Arabi", slug: "omar-hisham-al-arabi", collectionId: 1475482850),
        QCReciterEntry(name: "Omar Jabbie", slug: "omar-jabbie", collectionId: 1475482448),
        QCReciterEntry(name: "Osama Alsafi", slug: "osama-alsafi", collectionId: 1087854108),
        QCReciterEntry(name: "Qays Haail", slug: "qays-haail", collectionId: 1639307895),
        QCReciterEntry(name: "Raad Mohammad al Kurdi", slug: "raad-mohammad-al-kurdi", collectionId: 1087855153),
        QCReciterEntry(name: "Rabee Othman Hassan Mahmoud", slug: "rabee-othman-hassan-mahmoud", collectionId: 1832706449),
        QCReciterEntry(name: "Rachid Belaachya", slug: "rachid-belaachya", collectionId: 1087854130),
        QCReciterEntry(name: "Rachid Belalia", slug: "rachid-belalia", collectionId: 1087854879),
        QCReciterEntry(name: "Rachid Ifrad", slug: "rachid-ifrad", collectionId: 1087855033),
        QCReciterEntry(name: "Ramadan Chakour Hussein", slug: "ramadan-chakour-hussein", collectionId: 1087855503),
        QCReciterEntry(name: "Saad Al Qureshi", slug: "saad-al-qureshi", collectionId: 1475482722),
        QCReciterEntry(name: "Saad al-Ghamdi", slug: "saad-al-ghamdi", collectionId: 628019387),
        QCReciterEntry(name: "Saber Abdul Hakam", slug: "saber-abdul-hakam", collectionId: 1087857450),
        QCReciterEntry(name: "Sadaqat Ali", slug: "sadaqat-ali", collectionId: 823605899),
        QCReciterEntry(name: "Saeed Qalqily", slug: "saeed-qalqily", collectionId: 1832706523),
        QCReciterEntry(name: "Safwat Ash-Shawadfy", slug: "safwat-ash-shawadfy", collectionId: 1087858356),
        QCReciterEntry(name: "Sahl Yasin", slug: "sahl-yasin", collectionId: 823604477),
        QCReciterEntry(name: "Said Al-Shaalan", slug: "said-al-shaalan", collectionId: 1087858097),
        QCReciterEntry(name: "Salah Al Hashem", slug: "salah-al-hashem", collectionId: 823604498),
        QCReciterEntry(name: "Salah Al-Budair", slug: "salah-al-budair", collectionId: 721150884),
        QCReciterEntry(name: "Salah Ba-Uthman", slug: "salah-ba-uthman", collectionId: 1548182229),
        QCReciterEntry(name: "Salah Bukhatir", slug: "salah-bukhatir", collectionId: 687238388),
        QCReciterEntry(name: "Saleem Gaibie", slug: "saleem-gaibie", collectionId: 1087857857),
        QCReciterEntry(name: "Saleh Al Taleb", slug: "saleh-al-taleb", collectionId: 1087858066),
        QCReciterEntry(name: "Saleh bin Humaid", slug: "saleh-bin-humaid", collectionId: 1570606013),
        QCReciterEntry(name: "Salman Al-Utaybi", slug: "salman-al-utaybi", collectionId: 1016292617),
        QCReciterEntry(name: "Sami Al Dosari", slug: "sami-al-dosari", collectionId: 1087858728),
        QCReciterEntry(name: "Sami Al Hassan", slug: "sami-al-hassan", collectionId: 1087858223),
        QCReciterEntry(name: "Samih Taha Kandil", slug: "samih-taha-kandil", collectionId: 1087858432),
        QCReciterEntry(name: "Samir Belaachya", slug: "samir-belaachya", collectionId: 1087858783),
        QCReciterEntry(name: "Sapinah Mamat", slug: "sapinah-mamat", collectionId: 1087858142),
        QCReciterEntry(name: "Saud Al-Shuraim", slug: "saud-al-shuraim", collectionId: 817315462),
        QCReciterEntry(name: "Sayed Ramadan", slug: "sayed-ramadan", collectionId: 1087858158),
        QCReciterEntry(name: "Shaban Abdul Aziz Sayyad", slug: "shaban-abdul-aziz-sayyad", collectionId: 1087858977),
        QCReciterEntry(name: "Shahriar Parhizgar", slug: "shahriar-parhizgar", collectionId: 1087858856),
        QCReciterEntry(name: "Shawqy Hamed", slug: "shawqy-hamed", collectionId: 1561931755),
        QCReciterEntry(name: "Sherif Mostafa", slug: "sherif-mostafa", collectionId: 1832706524),
        QCReciterEntry(name: "Shirazad Taher", slug: "shirazad-taher", collectionId: 1087858823),
        QCReciterEntry(name: "Siratullo Raupov", slug: "siratullo-raupov", collectionId: 1087859904),
        QCReciterEntry(name: "Sulaiman Bin Ahmad Al Aouda", slug: "sulaiman-bin-ahmad-al-aouda", collectionId: 1832706479),
        QCReciterEntry(name: "Sultan Bin Ahmed Al-Owaid", slug: "sultan-bin-ahmed-al-owaid", collectionId: 1087859902),
        QCReciterEntry(name: "Syamsuri Firdaus", slug: "syamsuri-firdaus", collectionId: 1832706481),
        QCReciterEntry(name: "Taha Mohamed Abdulrahman Al-Fahad", slug: "taha-mohamed-abdulrahman-al-fahad", collectionId: 1087859062),
        QCReciterEntry(name: "Talaat Afifi", slug: "talaat-afifi", collectionId: 1087859449),
        QCReciterEntry(name: "Tarek Ibn Abdul Rahman Al-Hawass", slug: "tarek-ibn-abdul-rahman-al-hawass", collectionId: 1087859003),
        QCReciterEntry(name: "Tareq Abdulgani Daawob", slug: "tareq-abdulgani-daawob", collectionId: 1087859774),
        QCReciterEntry(name: "Tawfeeq As Sayegh", slug: "tawfeeq-as-sayegh", collectionId: 823604562),
        QCReciterEntry(name: "Turki Al Rumaih", slug: "turki-al-rumaih", collectionId: 1087859695),
        QCReciterEntry(name: "Usaamah Khayyat", slug: "usaamah-khayyat", collectionId: 1570612308),
        QCReciterEntry(name: "Ustaz Zamri", slug: "ustaz-zamri", collectionId: 1087860646),
        QCReciterEntry(name: "Wadee Hammadi Al Yamani", slug: "wadee-hammadi-al-yamani", collectionId: 1467167053),
        QCReciterEntry(name: "Waleed Al Shamsan", slug: "waleed-al-shamsan", collectionId: 1832706561),
        QCReciterEntry(name: "Waleed Atif", slug: "waleed-atif", collectionId: 1087860120),
        QCReciterEntry(name: "Waleed Idrees Al-Maneese", slug: "waleed-idrees-al-maneese", collectionId: 1087860161),
        QCReciterEntry(name: "Waleed Naehi", slug: "waleed-naehi", collectionId: 1087860236),
        QCReciterEntry(name: "Walid Al Dulaimi", slug: "walid-al-dulaimi", collectionId: 1087859790),
        QCReciterEntry(name: "Waseem Hendricks", slug: "waseem-hendricks", collectionId: 1764956366),
        QCReciterEntry(name: "Wassel Almethen", slug: "wassel-almethen", collectionId: 1087860195),
        QCReciterEntry(name: "Wishear Hayder Arbili", slug: "wishear-hayder-arbili", collectionId: 1087860199),
        QCReciterEntry(name: "Yahya Bin Abdul Aziz Al-Yahya", slug: "yahya-bin-abdul-aziz-al-yahya", collectionId: 1087860107),
        QCReciterEntry(name: "Yahya Hawwa", slug: "yahya-hawwa", collectionId: 1087860532),
        QCReciterEntry(name: "Yamani Mohamed Saleh", slug: "yamani-mohamed-saleh", collectionId: 1087861096),
        QCReciterEntry(name: "Yassen Al Jazairi", slug: "yassen-al-jazairi", collectionId: 1087860334),
        QCReciterEntry(name: "Yasser Al Dossari", slug: "yasser-al-dossari", collectionId: 823604747),
        QCReciterEntry(name: "Yasser Al Mazroyee", slug: "yasser-al-mazroyee", collectionId: 1087860608),
        QCReciterEntry(name: "Yasser Al-Faylakawi", slug: "yasser-al-faylakawi", collectionId: 1087860761),
        QCReciterEntry(name: "Yasser Mamdouh", slug: "yasser-mamdouh", collectionId: 1757812229),
        QCReciterEntry(name: "Yasser Qureshi", slug: "yasser-qureshi", collectionId: 1087860658),
        QCReciterEntry(name: "Yasser Salama", slug: "yasser-salama", collectionId: 1087860745),
        QCReciterEntry(name: "Yasser Sarhan Eldeeb", slug: "yasser-sarhan-eldeeb", collectionId: 1087860330),
        QCReciterEntry(name: "Youssef Edghouch", slug: "youssef-edghouch", collectionId: 1087861265),
        QCReciterEntry(name: "Yousuf Alshoaey", slug: "yousuf-alshoaey", collectionId: 1087861218),
        QCReciterEntry(name: "Yousuf Bin Noah Ahmad", slug: "yousuf-bin-noah-ahmad", collectionId: 1087861225),
        QCReciterEntry(name: "Yousuf Noorbhai", slug: "yousuf-noorbhai", collectionId: 1087861021),
        QCReciterEntry(name: "Yunus Aswailis [Warsh]", slug: "yunus-aswailis", collectionId: 1561932279),
        QCReciterEntry(name: "Zain Abu Kautsar", slug: "zain-abu-kautsar", collectionId: 1546238044),
        QCReciterEntry(name: "Zakaria Hamama", slug: "zakaria-hamama", collectionId: 1087861085),
        QCReciterEntry(name: "Zaki Daghistani", slug: "zaki-daghistani", collectionId: 1087862105),
        QCReciterEntry(name: "Ziad Ahmad Alhaj", slug: "ziad-ahmad-alhaj", collectionId: 1832706423),
        QCReciterEntry(name: "Ziyaad Patel", slug: "ziyaad-patel", collectionId: 1087861831),
    ]
}
